require "computer/operations/addition"
require "computer/operations/multiplication"
require "computer/operations/input"
require "computer/operations/output"
require "computer/operations/jump_if_true"
require "computer/operations/jump_if_false"
require "computer/operations/unary"
require "computer/operations/binary"
